//USER REGISTER
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";
export const OFF_MODAL = "OFF_MODAL";
//USER REGISTER ACTIVE
export const ACTIVE_USER_ACCOUNT_REUQEST = "ACTIVE_USER_ACCOUNT_REUQEST";
export const ACTIVE_USER_ACCOUNT_SUCCESS = "ACTIVE_USER_ACCOUNT_SUCCESS";
export const ACTIVE_USER_ACCOUNT_FAILURE = "ACTIVE_USER_ACCOUNT_FAILURE";
